import { useState } from 'react'
import { listTasks, listEmployees, updateTask, errMsg } from '../services/api'
import { useFetch } from '../hooks/useFetch'
import { Loading, ErrorBox, StatusBadge, Empty, PageHeader } from '../components/ui'
import { ListChecks } from 'lucide-react'

const STATUSES = ['', 'TODO', 'IN_PROGRESS', 'COMPLETED', 'OVERDUE']

export default function Onboarding() {
  const { data: employees } = useFetch(listEmployees)
  const [empFilter, setEmpFilter] = useState('')
  const [statusFilter, setStatusFilter] = useState('')
  const { data: tasks, loading, error, refetch } = useFetch(
    () => listTasks({ employee_id: empFilter || undefined, status: statusFilter || undefined }),
    [empFilter, statusFilter]
  )

  const change = async (id, status) => {
    try { await updateTask(id, status); refetch() }
    catch (e) { alert(errMsg(e)) }
  }

  return (
    <div>
      <PageHeader title="Onboarding Tasks" subtitle="Task plans generated by the Onboarding Agent for each employee" />

      <div className="flex flex-wrap gap-3 mb-4">
        <select className="input !w-auto" value={empFilter} onChange={e => setEmpFilter(e.target.value)}>
          <option value="">All employees</option>
          {(employees || []).map(e => <option key={e.id} value={e.id}>{e.name} ({e.id})</option>)}
        </select>
        <select className="input !w-auto" value={statusFilter} onChange={e => setStatusFilter(e.target.value)}>
          {STATUSES.map(s => <option key={s} value={s}>{s ? s.replaceAll('_', ' ') : 'All statuses'}</option>)}
        </select>
      </div>

      {loading && <Loading />}
      {error && <ErrorBox message={error} />}
      {tasks && tasks.length === 0 && <Empty icon={ListChecks} title="No tasks found" hint="Try a different filter, or upload a resume to generate a plan." />}

      {tasks && tasks.length > 0 && (
        <div className="card p-0 overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="text-left text-xs uppercase tracking-wide text-gray-500 border-b border-edge">
                <th className="px-5 py-3">Task</th>
                <th className="px-5 py-3">Employee</th>
                <th className="px-5 py-3">Category</th>
                <th className="px-5 py-3">Due</th>
                <th className="px-5 py-3">Priority</th>
                <th className="px-5 py-3">Status</th>
              </tr>
            </thead>
            <tbody>
              {tasks.map(t => (
                <tr key={t.id} className="border-b border-edge/50 hover:bg-panel/60">
                  <td className="px-5 py-3">
                    <div className={`font-medium ${t.status === 'COMPLETED' ? 'text-gray-500 line-through' : 'text-white'}`}>{t.title}</div>
                    <div className="text-xs text-gray-500 max-w-md truncate">{t.description}</div>
                  </td>
                  <td className="px-5 py-3 text-gray-300 whitespace-nowrap">{t.employee_name || t.employee_id}</td>
                  <td className="px-5 py-3 text-gray-400">{t.category || '—'}</td>
                  <td className="px-5 py-3 text-gray-300 whitespace-nowrap">{t.due_date || '—'}</td>
                  <td className="px-5 py-3"><StatusBadge status={t.priority} /></td>
                  <td className="px-5 py-3">
                    <select
                      value={t.status}
                      onChange={e => change(t.id, e.target.value)}
                      className="bg-base border border-edge rounded-lg text-xs px-2 py-1.5 text-gray-300 focus:outline-none"
                    >
                      {STATUSES.filter(Boolean).map(s => <option key={s}>{s}</option>)}
                    </select>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  )
}
